"""Add genre column to tracks

Revision ID: f6a31dd97c1e
Revises: 484fcb930575
Create Date: 2024-09-05 10:37:37.785016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a31dd97c1e'
down_revision = '484fcb930575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_constraint('playlist_tracks_track_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('playlist_tracks_playlist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tracks', ['track_id'], ['id'])
        batch_op.create_foreign_key(None, 'playlists', ['playlist_id'], ['id'])

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.drop_constraint('tracks_playlist_id_fkey', type_='foreignkey')
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tracks_playlist_id_fkey', 'playlists', ['playlist_id'], ['id'])
        batch_op.drop_column('genre')

    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('playlist_tracks_playlist_id_fkey', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('playlist_tracks_track_id_fkey', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
